export const products = [
  {
    id: 1,
    slug: "mg-freedom-gundam-ver-2",
    name: "MG Freedom Gundam Ver.2.0",
    category: "MG",
    price: 1250000,
    oldPrice: 1390000,
    badge: "-10%",
    rating: 4.9,
    reviews: 128,
    stock: 15,
    brand: "Bandai",
    image: "/products/mg-freedom.png",
  },
  {
    id: 2,
    slug: "rg-hi-nu-gundam",
    name: "RG Hi-Nu Gundam",
    category: "RG",
    price: 990000,
    oldPrice: 1100000,
    badge: "HOT",
    rating: 4.8,
    reviews: 96,
    stock: 9,
    brand: "Bandai",
    image: "/products/hinu.png",
  },
  {
    id: 3,
    slug: "hg-aerial-gundam",
    name: "HG Aerial Gundam",
    category: "HG",
    price: 450000,
    oldPrice: 475000,
    badge: "NEW",
    rating: 4.7,
    reviews: 68,
    stock: 22,
    brand: "Bandai",
    image: "/products/aerial.png",
  },
  {
    id: 4,
    slug: "mgex-strike-freedom",
    name: "MGEX Strike Freedom Gundam",
    category: "MG",
    price: 2650000,
    oldPrice: 0,
    badge: "PRE-ORDER",
    rating: 4.9,
    reviews: 54,
    stock: 4,
    brand: "Bandai",
    image: "/products/strike.svg",
  },
  {
    id: 5,
    slug: "pg-unleashed-rx-78-2",
    name: "PG Unleashed RX-78-2",
    category: "PG",
    price: 3850000,
    oldPrice: 0,
    badge: "LIMITED",
    rating: 4.9,
    reviews: 32,
    stock: 3,
    brand: "Bandai",
    image: "/products/rx78.svg",
  },
  {
    id: 6,
    slug: "rg-sazabi",
    name: "RG Sazabi",
    category: "RG",
    price: 1050000,
    oldPrice: 0,
    badge: "NEW",
    rating: 4.8,
    reviews: 87,
    stock: 12,
    brand: "Bandai",
    image: "/products/sazabi.svg",
  },
  {
    id: 7,
    slug: "mg-barbatos",
    name: "MG Barbatos",
    category: "MG",
    price: 1050000,
    oldPrice: 0,
    badge: "BEST",
    rating: 4.8,
    reviews: 71,
    stock: 10,
    brand: "Bandai",
    image: "/products/barbatos.svg",
  },
  {
    id: 8,
    slug: "godhand-nipper-spn-120",
    name: "GodHand Nipper SPN-120",
    category: "TOOLS",
    price: 450000,
    oldPrice: 0,
    badge: "TOOL",
    rating: 4.7,
    reviews: 45,
    stock: 30,
    brand: "GodHand",
    image: "/products/nipper.svg",
  },
  {
    id: 9,
    slug: "tamiya-panel-line-black",
    name: "Tamiya Panel Line Accent Black",
    category: "PAINT",
    price: 120000,
    oldPrice: 0,
    badge: "PAINT",
    rating: 4.6,
    reviews: 52,
    stock: 50,
    brand: "Tamiya",
    image: "/products/paint.svg",
  },
] as const;
export type Product = (typeof products)[number];
export const formatPrice = (n: number) =>
  new Intl.NumberFormat("vi-VN").format(n) + "đ";
